CREATE DATABASE
IF NOT EXISTS `admin_db`;
CREATE DATABASE
IF NOT EXISTS `member_db`;
CREATE DATABASE
IF NOT EXISTS `publishing_db`;
GRANT ALL PRIVILEGES ON *.* TO 'administrator'@'%';
FLUSH PRIVILEGES;
